# Spring Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/medical_topics_db
spring.datasource.username=postgres
spring.datasource.password=Erbol
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring MVC properties for multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# Cloudinary Configuration
cloudinary.cloud_name=dluzoouvw
cloudinary.api_key=724673665684542
cloudinary.api_secret=NWS0ZhvT2aYJRbLmVzoykq574dQ

# Logging
logging.level.org.springframework.web=DEBUG
# Corrected line below:
logging.level.com.example.medicaltopic=DEBUG

spring.main.allow-bean-definition-overriding=true

# Server Port
server.port=8080

# Springdoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html